services:
  - type: web
    name: hackthehaze-project
    env: python
    region: ohio  # Choose the appropriate region for your users
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0  # Choose an appropriate Python version
      - key: ALLOW_ALL_ORIGINS
        value: false      - key: FRONTEND_URL
        # Frontend URL on Vercel
        value: https://hackthehaze-project.vercel.app
    autoDeploy: true
